### ISSUE TITLE
License file

### ISSUE THREAD

**Issue by jakirkham** [JdeH/Numscrypt#3]
Please include a license file and add it to the `MANIFEST.in` file. This is needed to comply with this provision of the Apache 2.0 license.

> "Work" shall mean the work of authorship, whether in Source or Object form, made available under the License, as indicated by a copyright notice that is included in or attached to the work (an example is provided in the Appendix below).

> "Derivative Works" shall mean any work, whether in Source or Object form, that is based on (or derived from) the Work and for which the editorial revisions, annotations, elaborations, or other modifications represent, as a whole, an original work of authorship. For the purposes of this License, Derivative Works shall not include works that remain separable from, or merely link (or bind by name) to the interfaces of, the Work and Derivative Works thereof.

> ...

> You must give any other recipients of the Work or Derivative Works a copy of this License...

**Comment by JdeH** [comment]
Hi,

Thanks for the feedback.

There's a license file in the distribution, called license_reference.txt.
It is included in the distribution by virtue of the following line of MANIFEST.in:

`global-include *.py *.js *.rst *.html *.css *.lyx *.pdf *.png *.gif *.jpg *.txt *.jar *.bat *`

Is this indeed what you mean, or does something else that has to be done?

Kind regards
Jacques

**Comment by jakirkham** [comment]
Ah, thanks, sorry for the noise.

**Comment by JdeH** [comment]
No problem!
